### ISSUE TITLE
type.toUpperCase is not a function

### ISSUE THREAD

**Issue by evandegr** [odysseyscience/react-router-proxy-loader#10]
`Uncaught TypeError: type.toUpperCase is not a function`

Is showing up when I'm trying to load a route like this -> 
`routerManager.add(require('react-router-proxy!/web/app/operations/src/app.js'), 'operations');`

Expanded it looks like its coming from here:

`function autoGenerateWrapperClass(type) {
      return ReactClass.createClass({
        tagName: type.toUpperCase(),
        render: function render() {
          return new ReactElement(type, null, null, null, null, this.props);
        }
    });
}`

RouterManager is just a wrapper I have on top of ReactRouter which passes the path and the handler.

I'm using:

React v0.13.3
React-router v0.13.3
React-router-proxy-loader v0.3.0

Anyone seen something like this?

**Comment by seanadkinson** [comment]
Hi @evandegr.  I've never seen anything like this.  What library is `autoGenerateWrapperClass` from?  Is that from core React?  Can you put a breakpoint in there, and go up the stack trace and see what is happening?

Need to be able to reproduce to help out, and not sure what is going here.  Maybe put up a jsfiddle that shows the issue.

**Comment by evandegr** [comment]
Hey yeah sorry it was a versioning issue with something else.
