### ISSUE TITLE
Track loading status

### ISSUE THREAD

**Issue by ghost** [odysseyscience/react-router-proxy-loader#11]
How i can track loading status (e.g i want to show loader while loading component ) ?

**Comment by seanadkinson** [comment]
This library doesn't support anything like that.  Think of this library as mimicking the behavior when you click a link in your browser that opens a different page with a full render.  The browser spins on the current page while the next page loads.  This library causes react-router to not change the current page, until the next page is ready to render (i.e. all the javascript is loaded).

If you wanted to show a Loading spinner or something, you wouldn't even need this library.  Just render components with the spinner, kick off ajax calls in `componentDidMount`, and `setState` and render something else when ready.  Make sense?

**Comment by ghost** [comment]
Yes, thanks
