### ISSUE TITLE
Update peerDependency of react-router 

### ISSUE THREAD

**Issue by franferdez** [odysseyscience/react-router-proxy-loader#12]
I tried the loader with the version 1.0.0-rc1 of react-router and it works fine. But npm gives trouble with the peerDependencies. It would be really nice to update this.

**Comment by grrowl** [comment]
+1 I'm feeling this now, though I suspect it's because react-router v1.0 is still in RC. I'll provide a PR to reflect this (since I'll be pointing my dependent react-router entry to the fork anyway)

**Comment by grrowl** [comment]
It seems like there's a better approach to lazy-loading in v1 than proxying every route's component, see https://github.com/rackt/react-router/blob/master/docs/guides/advanced/DynamicRouting.md:

``` js
const CourseRoute = {
  path: 'course/:courseId',

  getChildRoutes(location, callback) {
    require.ensure([], function (require) {
      callback(null, [
        require('./routes/Announcements'),
        require('./routes/Assignments'),
        require('./routes/Grades'),
      ])
    })
  },

  getComponents(location, callback) {
    require.ensure([], function (require) {
      callback(null, require('./components/Course'))
    })
  }
}
```

**Comment by seanadkinson** [comment]
Oh nice, haven't seen that yet.  We will be upgrading our `react-router` next month, so I suspect we'll get all up to date then.

I'll take a look at this PR in just a sec.

**Comment by seanadkinson** [comment]
Pushed version `0.4.0` to NPM with this change.  Sorry for the delay on this @franferdez, busy week.
