### ISSUE TITLE
Entry point not running

### ISSUE THREAD

**Issue by sebasgarcep** [odysseyscience/react-router-proxy-loader#16]
I set up a hapi server to serve my main bundle from /public. Now I want to split the app's code to accelerate startup time, but when I use this loader my entry point doesn't get loaded. Note that if I remove the module loaders setting it works fine and as intended (just in one bundle).

I have the following setup:

app/js/index.js (before transpiling)

``` javascript
import React from 'react';
import ReactDOM from 'react-dom';
import {Router, Route, Link, browserHistory} from 'react-router';

import Test from './test';

class App extends React.Component {

  render () {
    return (
      <div>
        <h1>Hello world</h1>
        <Link to='/test'><button>test</button></Link>
      </div>
    );
  }

}

let routes = (
  <Router history={browserHistory}>
    <Route path='/' component={App}/>
    <Route path='/test' component={Test}/>
  </Router>
);

ReactDOM.render(routes, document.getElementById('app'));
```

app/js/test.js (before transpiling)

``` javascript
import React from 'react';
import {Link} from 'react-router';

export default class Test extends React.Component {
  render() {
    return (
      <div>
        <h1>Test route</h1>
        <Link to='/'><button>home</button></Link>
      </div>
    );
  }
}
```

app/js/server.js (before transpiling)

``` javascript
import Hapi from 'hapi';
import inert from 'inert';
import path from 'path';

const server = new Hapi.Server({
  connections: {
    routes: {
      files: {
        relativeTo: path.join(__dirname, '..', '..', 'public')
      }
    }
  }
});

server.connection({ port: 5000 });

server.register(inert, () => {});

server.route({
  method: 'GET',
  path: '/public/{path*}',
  handler: {
    directory: {
      path: '.',
      redirectToSlash: true,
      index: true
    }
  }
});

server.route({
  method: 'GET',
  path: '/{path*}',
  handler: {
    file: req => 'index.html'
  }
});

server.start(() => {
  console.log('Server running at: ' + server.info.uri);
});
```

webpack.config.js

``` javascript
const webpack = require('webpack');

module.exports = {

  entry: './app/js/index.js',

  output: {
    path: './public/',
    filename: 'bundle.min.js'
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'react-router-proxy'
      }
    ]
  }
}
```

public/index.html:

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <div id="app"></div>
    </script><script src="/public/bundle.min.js"></script>
  </body>
</html>
```

dependencies:

``` json
"react-router": "^2.0.0-rc5",
"react": "^0.14.6",
"react-dom": "^0.14.6",
"react-router-proxy-loader": "^0.4.3",
"hapi": "^12.1.0",
"inert": "^3.2.0",
"webpack": "^1.12.12"
```

**Comment by seanadkinson** [comment]
What do you see in the network tab of chrome dev tools?  Are requests made, just not served?  Are there javascript errors?

You may need to set your webpack `publicPath` to make sure it is requesting the files dynamically from the correct location.  If you need to set the public path dynamically, you need to use `__webpack_public_path__`.

Please provide more info about why your entrypoint isn't loading at all.  Chrome dev tools should be very helpful here.

**Comment by sebasgarcep** [comment]
I set up a project with this structure at https://github.com/sebasgarcep/react-router-proxy-loader-example. On the console there were no errors. I'll look into publicPath meanwhile.

**Comment by sebasgarcep** [comment]
I added `publicPath` and excluded `index.js` from the regex match and it worked. Turns out the entry point was being put into another chunk and for some reason, even with explicit loading of this other bundle, it didn't run.

**Comment by seanadkinson** [comment]
Sounds good.  Will close issue.

**Comment by sebasgarcep** [comment]
Shouldn't this detail be documented?

**Comment by seanadkinson** [comment]
Perhaps, but all this repo does is provide webpack code splitting.  The webpack documentation tells you how to correctly configure the code splitting.  I think most applications work okay with the default settings, which is why this issue hasn't come up before.

What `publicPath` did you need to set for webpack?  And I wasn't sure what you meant when you said you "excluded index.js", can you elaborate?

**Comment by sebasgarcep** [comment]
I set `publicPath` to `/public/` which is where I serve all static content. And by excluding index.js I meant that the regex that matches the loader in the `webpack.config.js` file no longer matches positively for the entry point. Am I clear?

**Comment by seanadkinson** [comment]
I'm by no means an expert, but I think you are doing a couple things out of the ordinary that may have made this harder.

First, I don't think you usually have the browser request files using `/public` in the path.  Rather, node serves matching static files that it finds in the `public` folder given the request path.  So if a request for `/favicon.ico` is made and there exists a `public/favicon.ico` file in your project, that would be served up.  This means your `/css`, `/img`, etc., can be served up from `public/css`, `public/img`, etc.

Second, `react-router-proxy-loader` has typically been used straight inside the `Routes.jsx` file.  Although I know that doesn't exist in the latest react-router version... are you using the latest version?  By using webpack version `react-router-proxy!./User.jsx` or whatever, no need to regex-filter the included files.  Make sense?

Regardless, if you'd like to submit a PR with some extra documentation, I'd gladly review and accept.

Thanks!
