### ISSUE TITLE
Creating files with hashed names

### ISSUE THREAD

**Issue by maiopirata** [odysseyscience/react-router-proxy-loader#22]
I'm using this package@0.5.1 with react-router@2.4.

in my route file I have:

```
<IndexRoute 
            component={ require('react-router-proxy?name=[Home]!./../components/Home/Home.react.js') } 
            onEnter={ endTransition } />
```

and in my webpack.config.js I have:

```
{ 
      test: /\.js$/,
      include: /app\/js\/components\/Home\/Home.react.*/,
      loaders: ['react-router-proxy?[name]', 'babel']
}
```

So in output I have many splitted js files that are charged at the specific route! This is great!
The problem is that I having files named 0.0.js 1.1.js etc.
I would like to obtain some old fashioned lfqdkjfqljfqlkj.js files..

I thought that using [name] should give me the Home in the files but I'm missing something.

Any help would be really appreciated!
thanks

**Comment by seanadkinson** [comment]
Issue could be that you shouldn't have `?name=[Home]`, with square-brackets.  Try just `?name=Home`.

**Comment by maiopirata** [comment]
I get exactly the same result when I put:

```
<IndexRoute 
            component={ require('react-router-proxy?name=[Home]!./../components/Home/Home.react.js') } 
            onEnter={ endTransition } />
```

or

```
<IndexRoute 
            component={ require('react-router-proxy?name=Home!./../components/Home/Home.react.js') } 
            onEnter={ endTransition } />
```

**Comment by seanadkinson** [comment]
In your webpack config, you may need to set the `name` query param like so:

```
{ 
      test: /\.js$/,
      include: /app\/js\/components\/Home\/Home.react.*/,
      loaders: ['react-router-proxy?name=[name]', 'babel']
}
```

**Comment by maiopirata** [comment]
thanks! that was it!

Do you think that the Readme is someway confusing for this?
