### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by moliver-bb** [odysseyscience/react-router-proxy-loader#23]
I just had a couple questions about the documentation... is it required to run the babel loader twice? 

```

loaders: [
    {
        test: /\.js$/,
        exclude: /src\/Pages/,
        loader: 'babel',
    },
    {
        test: /\.js$/,
        include: /src\/Pages/,
        loaders: ['react-router-proxy?name=routes/[name]', 'babel'],
    }
],
```

also can you expand on this:
**0.4.2
Added support for ES6 modules**

does this mean we can import those pages like this:

```
//routes.js

import App from './app.jsx'
import Users from './users.jsx'
import { Route } from 'react-router'

const routes = <Route component={App} path='/'>
  <Route component={Users} path='users' />
</Route>
```

or will that just lazy load all the pages at once when the routes.js page is loaded?

thanks for any help with this

**Comment by seanadkinson** [comment]
I didn't personally write that bit of documentation, or the code for the ES6 modules, but I'll answer as best I can.

First question - I don't think the babel loader is being run twice, as the `exclude/include` create two disjoint sets of files.  So `babel` would still only parse each file once.

Second question - If you `import` the modules that way, they've already been loaded at "compile time" (so to speak), and you've lost the benefit of lazy-loading.  The PR for that "ES6" release note was really about lazy loading the ES6 way (or is it ES7 I wonder).  I think the `System.import` is where those changes would now work.

Let me know if you have any other questions, or that doesn't make sense.

**Comment by moliver-bb** [comment]
ah thanks! I misread the "exclude" as "include"
