### ISSUE TITLE
0.13.x

### ISSUE THREAD

**Issue by JGSolutions** [odysseyscience/react-router-proxy-loader#6]
Can this work with react.js 0.13 and up? NPM installation complaining...

npm ERR! peerinvalid The package react-router does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router-proxy-loader@0.2.3 wants react-router@^0.12.0

**Comment by seanadkinson** [comment]
Looks like the API hasn't changed on `willTransitionTo` and `willTransitionFrom`, so it will probably work for 0.13.  I'll push up a branch, and maybe you can test it out?  If all is well, I'll push `0.3`

**Comment by seanadkinson** [comment]
Can you try adding this to your `package.json`?

```
...
"react-router-proxy-loader": "odysseyscience/react-router-proxy-loader#react-router-0.13",
...
```

If all looks good, I'll push an update to NPM.

**Comment by JGSolutions** [comment]
thanks for the reply.

i did this as you requested:
"react-router-proxy-loader": "odysseyscience/react-router-proxy-loader#react-router-0.13",

npm installation all seemed fine but I still didn't implement the code yet. So far so good.

Thanks

**Comment by grrowl** [comment]
``` json
  "react-router-proxy-loader": "odysseyscience/react-router-proxy-loader#react-router-0.13",
```

works as expected with react and react-router 0.13.x, although I'm getting the following warning in the console: 

```
Warning: Don't set .props.ref of the React component <ReactProxy />. Instead, specify 
the correct value when initially creating the element or use React.cloneElement to make 
a new element with updated props.
```

**Comment by seanadkinson** [comment]
Okay, I added `object-assign` as a dependency, and am using that to set the `ref` of the child component now.  Can you see if that fixes the warning for you?

**Comment by grrowl** [comment]
Yup, although I had to `npm install object-assign --save` within my main project to get it to work (otherwise it was throwing errors in my own code, I assume a result of webpack-level rewriting).

Here are the errors, maybe consider adding a note to the README about its requirement? or could it be satisfied by `peerDependencies`?

```
ERROR in ./src/views/styleguide/route.jsx
Module not found: Error: Cannot resolve module 'object-assign' in /Users/tom/Documents/magicland/auth.comet.is/src/views/styleguide
 @ ./src/views/styleguide/route.jsx 2:13-37

ERROR in ./src/server/notfoundroute.jsx
Module not found: Error: Cannot resolve module 'object-assign' in /Users/tom/Documents/magicland/auth.comet.is/src/server
 @ ./src/server/notfoundroute.jsx 2:13-37

ERROR in ./src/server/notsupportedroute.jsx
Module not found: Error: Cannot resolve module 'object-assign' in /Users/tom/Documents/magicland/auth.comet.is/src/server
 @ ./src/server/notsupportedroute.jsx 2:13-37
```

**Comment by seanadkinson** [comment]
Ah, that makes sense, since it wouldn't necessarily have `object-assign` available from the place that your component is calling `require('object-assign')`.  Yes, I think adding that as a peer dependency would be correct, and then requiring people add it to their project themselves.  I'll make that change.

**Comment by seanadkinson** [comment]
Didn't like the idea of requiring people add something to their `package.json`, so I just yanked a small version of `object-assign` and put it in the code.  I think the 4 lines of code is a good tradeoff for the portability.

If you want to pull the latest code, remove your `object-assign` dependency, and let me know if it looks good, I'll push a new version.

Thanks for you help.

**Comment by grrowl** [comment]
I agree, it's a bit much overhead for such a little thing. ~~I fucked up, will update in a sec~~

**Comment by grrowl** [comment]
Looks good to me, no object-assign installed, no dependency errors, does the hot updating thing, :shipit:

**Comment by seanadkinson** [comment]
Cool, I'll push an updated version in a moment

**Comment by seanadkinson** [comment]
Just pushed `v0.3.0` with support for `react-router@0.13`

Thanks for helping make sure this was good to go :+1:
